# Generated by Django 2.2.20 on 2021-10-09 14:09

from django.db import migrations


def load_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats = Flat.objects.all()
    for flat in flats:
        owner, created_owner = (
            Owner.objects
            .get_or_create(owner=flat.owner,
                           owners_phonenumber=flat.owners_phonenumber,
                           defaults={
                                'owner_pure_phone': flat.owner_pure_phone,
                            })
            )


def delete_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')

    Owner.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_add_new_model'),
    ]

    operations = [
        migrations.RunPython(load_owners,
                             delete_owners)
    ]
