# Generated by Django 2.2.20 on 2021-10-09 15:41

from django.db import migrations


def set_relation(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    db_alias = schema_editor.connection.alias

    flats = Flat.objects.using(db_alias).all()
    for flat in flats:
        owner, _ = (
            Owner.objects.using(db_alias)
            .get_or_create(owner=flat.owner,
                           owners_phonenumber=flat.owners_phonenumber,
                           defaults={
                                'owner_pure_phone': flat.owner_pure_phone,
                            })
            )
        flat.owners.set([owner])


def clear_relation(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    db_alias = schema_editor.connection.alias

    owners = Owner.objects.using(db_alias).all()
    for owner in owners:
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_add_content_to_owners_model'),
    ]

    operations = [
        migrations.RunPython(set_relation,
                             clear_relation)
    ]
